#!/usr/bin/env python3
"""
gkeepbak
  glob most recent backup, compare via keep api, write new bakfile if changed

desc:
  - maintains zstd-compressed backups of google keep data
  - globs exiting serialized state backups in $1 dir, reads most recent
  - if no backup files, obtain full keep data anew from api (expensive)
  - otherwise, uses api to sync from upstream, does incremental download
  - if changed records, write new serialized json for comparison next time
  - outputs difference with previous run to stdout (ie, intended for cron)
  - requires $GKEEPBAK_EMAIL for account, $GKEEPBAK_TOKEN for master token

deps:
  - https://github.com/kiwiz/gkeepapi/

"""
__url__     = 'https://github.com/smemsh/utilpy/'
__author__  = 'Scott Mcdermott <scott@smemsh.net>'
__license__ = 'GPL-2.0'
__devskel__ = '0.12.2'

import sys
if sys.hexversion < 0x030a00f0:
    sys.exit("minpython: %s" % sys.hexversion)

import argparse

from compression import zstd
from subprocess import call, DEVNULL
from functools import partial
from select import select
from shutil import which
from stat import S_IWUSR, S_IRUSR
from copy import deepcopy
from glob import glob

from json import dumps, load
from json.decoder import JSONDecodeError

from os.path import basename, splitext, dirname, isdir, exists, abspath
from os import (
    getenv, unsetenv,
    getcwd, chdir, makedirs,
    access, R_OK, W_OK,
    open as osopen,
    close as osclose,
    EX_OK as EXIT_SUCCESS,
    EX_SOFTWARE as EXIT_FAILURE,
)

from datetime import datetime as dt
from difflib import unified_diff as udiff

import gkeepapi

###

def msg(*args, **kwargs):
    print(*args, **kwargs)

def err(*args, **kwargs):
    msg(*args, file=sys.stderr, **kwargs)

def bomb(*args, **kwargs):
    err(*args, **kwargs)
    exit(EXIT_FAILURE)

###

def process_args():

    global args

    def addarg(p, vname, help=None, /, **kwargs):
        p.add_argument(vname, help=help, **kwargs)

    p = argparse.ArgumentParser(
        prog            = invname,
        description     = __doc__.strip(),
        allow_abbrev    = False,
        formatter_class = argparse.RawTextHelpFormatter,
    )
    addarg(p, 'bakdir')
    args = p.parse_args(args)
    bakdir = args.bakdir or getcwd()

    return abspath(bakdir.rstrip('/'))


def check_sanity(dest):

    if not isdir(dest):
        bomb(f"backup directory '{dest}' invalid")

    if not exists(dest):
        try: makedirs(dest)
        except: bomb(f"backup dir '{dest}' dne or bad mkdir")

    elif not isdir(dest):
        bomb(f"refusing overwrite of '{dest}' (not a directory)")

    if not access(dest, W_OK):
        bomb(f"cannot write to destdir '{dest}'")

    if not uplink(wait=21600):
        bomb(f"no uplink after 0.25 days")


def uplink(count=3, delay=100, wait=None, secs=60, host='8.8.8.8'):
    sofar = 0
    if wait and wait <= secs:
        bomb("wait must exceed secs")
    while True:
        start = monotonic()
        cmd = f"ping -i{delay / 1000} -c{count} -w3 {host}"
        if call(cmd.split(), stdout=DEVNULL) == EXIT_SUCCESS: return True
        if wait is None: return False
        if wait > 0:
            sofar += monotonic() - start
            if sofar >= wait: return False
        sleep(secs)
        sofar += secs


def gkeepbak(bakdir):

    (authtok := getenv('GKEEPBAK_TOKEN')) or bomb("authtok unset")
    (email := getenv('GKEEPBAK_EMAIL')) or bomb("email unset")

    keep = gkeepapi.Keep()

    chdir(bakdir)
    if statefiles := glob('state-20????????????.json.zst'):
        latest = sorted(statefiles)[-1]
        infile = open(latest, 'rb')
        zinfile = zstd.open(infile)
        try: olddata = load(zinfile)
        except JSONDecodeError:
            bomb(f"problem parsing json from {latest}")
    else:
        err("initial run, full download")
        olddata = None

    # must pass a copy because it gets mutated internally, see our issue 192
    keep.authenticate(email, authtok, state=deepcopy(olddata))
    newdata = keep.dump()
    oldnodes = olddata['nodes']
    newnodes = newdata['nodes']

    # we'll test if last run differs, but we remove sortValue, so use copies
    fn = lambda d: d['id']
    oldcp = sorted(deepcopy(oldnodes), key=fn)
    newcp = sorted(deepcopy(newnodes), key=fn)

    # sortValues change just by looking at notes, so ignore for change detect
    for cp in oldcp, newcp:
        for i in range(len(cp)):
            del cp[i]['sortValue']

    bothsame = False
    if len(oldnodes) == len(newnodes):
        for i in range(len(oldcp)):
            # if ids changed, they differ
            if oldcp[i]['id'] != newcp[i]['id']: break
            else: bothsame = True

    # deep-compare nodes using their serialized form (less deleted sortValue)
    oldjson = dumps(oldcp, sort_keys=True)
    newjson = dumps(newcp, sort_keys=True)
    if bothsame and oldjson == newjson:
        exit(EXIT_SUCCESS)  # no need for new bakfile

    fn = lambda f: f['timestamps']['updated']
    oldlast = fn(sorted(oldnodes, key=fn)[-1])
    newlast = fn(sorted(newnodes, key=fn)[-1])

    fmt = "%Y%m%d%H%M%S"
    old = dt.fromisoformat(oldlast)
    new = dt.fromisoformat(newlast)
    now = dt.now().strftime(fmt)
    stamp = new.strftime(fmt)
    since = (new - old).total_seconds() / 60 / 60

    outname = f"state-{now}.json.zst"
    outmode = S_IWUSR | S_IRUSR  # python open() does not have file mode parm
    outfile = open(outname, 'xb', opener=partial(osopen, mode=outmode))
    zoutfile = zstd.open(outfile, 'w')
    # json.load() supports bytes, but .dump() can only write strings
    #dump(newdata, zoutfile)

    newbytes = dumps(newdata).encode()
    zoutfile.write(newbytes)
    zoutfile.close()

    # display changes since last run.  since nodes could have been added or
    # removed, and have fairly random keys, diffing the full oldjson/newjson
    # (with indent) can contain a bunch of bogus delta and make eyeballing
    # difficult.  so we do compare each node separately.
    #
    allids = set([node['id'] for node in oldcp + newcp])
    olddict = {d['id']: d for d in oldcp}
    newdict = {d['id']: d for d in newcp}
    msg(f"newest: {stamp}, since: {since:0.2f} hours, diffs:")
    for k in allids:
        params = list()
        for d in olddict, newdict:
            parm = {}
            node = d.get(k, {})
            dump = "" if not node else dumps(node, sort_keys=True, indent=2)
            parm['name'] = node.get('title', node.get('id', '/dev/null'))
            parm['lines'] = dump.splitlines(keepends=True)
            params.append(parm)
        args = params[0]['lines'], params[1]['lines']
        kwargs = {'fromfile': params[0]['name'], 'tofile': params[1]['name']}
        if diff := list(udiff(*args, **kwargs)):
            if not (diff := "".join(diff)) or diff.isspace():
                continue
            else:
                print("\n" + diff)


def main():

    if debug == 1:
        breakpoint()

    bakdir = process_args()
    check_sanity(bakdir)

    try: subprogram = globals()[invname]
    except (KeyError, TypeError):
        from inspect import trace
        if len(trace()) == 1: bomb("unimplemented")
        else: raise

    return subprogram(bakdir)

###

if __name__ == "__main__":

    invname = basename(sys.argv[0])
    args = sys.argv[1:]

    from bdb import BdbQuit
    if debug := int(getenv('DEBUG') or 0):
        import pdb
        from pprint import pp
        err('debug: enabled')
        unsetenv('DEBUG')  # otherwise forked children hang

    try: main()
    except BdbQuit: bomb("debug: stop")
    except SystemExit: raise
    except KeyboardInterrupt: bomb("interrupted")
    except:
        from traceback import print_exc
        print_exc(file=sys.stderr)
        if debug: pdb.post_mortem()
        else: bomb("aborting...")
    finally:  # cpython bug 55589
        try: sys.stdout.flush()
        finally:
            try: sys.stdout.close()
            finally:
                try: sys.stderr.flush()
                except: pass
                finally: sys.stderr.close()
