#!/usr/bin/env python3
"""
gkeepbak
  read old state backup file, compare to api, make new backup if changed

desc:
  - maintains zstd-compressed backups of google keep data
  - globs backup files in arg1 dir, reads most recent serialized state
  - if no backup files, obtain keep data anew from api (expensive)
  - otherwise, uses api to sync from upstream, does incremental download
  - if changed records, write new serialized json for comparison next time
  - requires $GKEEPBAK_EMAIL for account, $GKEEPBAK_TOKEN for master token

deps:
  - https://github.com/kiwiz/gkeepapi/

"""
__url__     = 'https://github.com/smemsh/utilpy/'
__author__  = 'Scott Mcdermott <scott@smemsh.net>'
__license__ = 'GPL-2.0'
__devskel__ = '0.10.0'

from sys import exit, hexversion
if hexversion < 0x030e00f0: exit("minpython: %s" % hexversion)

import argparse

from compression import zstd
from subprocess import call
from functools import partial
from select import select
from shutil import which
from stat import S_IWUSR, S_IRUSR
from copy import deepcopy
from glob import glob
from sys import argv, stdin, stdout, stderr

from json import dumps, load
from json.decoder import JSONDecodeError

from os.path import basename, splitext, dirname, isdir, exists, abspath
from os import (
    getenv, unsetenv,
    getcwd, chdir, makedirs,
    access, R_OK, W_OK,
    open as osopen,
    close as osclose,
    EX_OK as EXIT_SUCCESS,
    EX_SOFTWARE as EXIT_FAILURE,
)

from datetime import datetime as dt
from difflib import unified_diff as udiff

import gkeepapi

###

def msg(*args, **kwargs):
    print(*args, **kwargs)

def err(*args, **kwargs):
    kwargs |= {'file': stderr}
    msg(*args, **kwargs)

def bomb(*args, **kwargs):
    err(*args, **kwargs)
    exit(EXIT_FAILURE)

###

def process_args():

    global args

    def addarg(p, vname, help=None, /, **kwargs):
        p.add_argument(vname, help=help, **kwargs)

    p = argparse.ArgumentParser(
        prog            = invname,
        description     = __doc__.strip(),
        allow_abbrev    = False,
        formatter_class = argparse.RawTextHelpFormatter,
    )
    addarg(p, 'bakdir')
    args = p.parse_args(args)
    bakdir = args.bakdir or getcwd()

    return abspath(bakdir.rstrip('/'))


def check_sanity(dest):

    if not isdir(dest):
        bomb(f"backup directory '{dest}' invalid")

    if not exists(dest):
        try: makedirs(dest)
        except: bomb(f"backup dir '{dest}' dne or bad mkdir")

    elif not isdir(dest):
        bomb(f"refusing overwrite of '{dest}' (not a directory)")

    if not access(dest, W_OK):
        bomb(f"cannot write to destdir '{dest}'")

    if which('uplink'):
        retry_for_secs = 21600
        if call(f"uplink -w {retry_for_secs}".split()) != 0:
            bomb(f"no uplink after {retry_for_secs} secs")
    else:
        err("skipping uplink check, no such executable")


def gkeepbak(bakdir):

    (authtok := getenv('GKEEPBAK_TOKEN')) or bomb("authtok unset")
    (email := getenv('GKEEPBAK_EMAIL')) or bomb("email unset")

    keep = gkeepapi.Keep()

    chdir(bakdir)
    if statefiles := glob('state-20????????????.json.zst'):
        latest = sorted(statefiles)[-1]
        infile = open(latest, 'rb')
        zinfile = zstd.open(infile)
        try: olddata = load(zinfile)
        except JSONDecodeError:
            bomb(f"problem parsing json from {latest}")
    else:
        err("initial run, full download")
        olddata = None

    # must pass a copy because it gets mutated internally, see our issue 192
    keep.authenticate(email, authtok, state=deepcopy(olddata))
    newdata = keep.dump()
    oldnodes = olddata['nodes']
    newnodes = newdata['nodes']

    # we'll test if last run differs, but we remove sortValue, so use copies
    fn = lambda d: d['id']
    oldcp = sorted(deepcopy(oldnodes), key=fn)
    newcp = sorted(deepcopy(newnodes), key=fn)

    # sortValues change just by looking at notes, so ignore for change detect
    for i in range(len(oldcp)):
        del oldcp[i]['sortValue'], newcp[i]['sortValue']

    bothsame = False
    if len(oldnodes) == len(newnodes):
        for i in range(len(oldcp)):
            # if ids changed, they differ
            if oldcp[i]['id'] != newcp[i]['id']: break
            else: bothsame = True

    # deep-compare using serialized data, less sortValue and last-updated
    oldjson = dumps(oldcp, sort_keys=True, indent=2)
    newjson = dumps(newcp, sort_keys=True, indent=2)
    if bothsame and oldjson == newjson:
        exit(EXIT_SUCCESS)  # no need for new bakfile

    fn = lambda f: f['timestamps']['updated']
    oldlast = fn(sorted(oldnodes, key=fn)[-1])
    newlast = fn(sorted(newnodes, key=fn)[-1])

    fmt = "%Y%m%d%H%M%S"  # still used
    old = dt.fromisoformat(oldlast)
    new = dt.fromisoformat(newlast)
    now = dt.now().strftime(fmt)  # still used
    stamp = new.strftime(fmt)
    since = (new - old).total_seconds() / 60 / 60
    #err(f"newest: {stamp}, since: {since:0.2g} hours")

    outname = f"state-{now}.json.zst"
    outmode = S_IWUSR | S_IRUSR  # python open() does not have file mode parm
    outfile = open(outname, 'xb', opener=partial(osopen, mode=outmode))
    zoutfile = zstd.open(outfile, 'w')
    # json.load() supports bytes, but .dump() can only write strings
    #dump(newdata, zoutfile)

    newbytes = dumps(newdata).encode()
    zoutfile.write(newbytes)
    zoutfile.close()

    # display a diff for what changed.  google seems to "expire" some old
    # notes without me telling it to, which contradicts posts about non-expiry
    # and is not documented.  currently investigating.
    #
    oldl = oldjson.splitlines(keepends=True)
    newl = newjson.splitlines(keepends=True)
    oldname = splitext(latest)[0]
    newname = splitext(outname)[0]
    print("".join(udiff(oldl, newl, fromfile=oldname, tofile=newname)))

def main():

    if debug == 1:
        breakpoint()

    bakdir = process_args()
    check_sanity(bakdir)

    try: subprogram = globals()[invname]
    except (KeyError, TypeError):
        from inspect import trace
        if len(trace()) == 1: bomb("unimplemented")
        else: raise

    return subprogram(bakdir)

###

if __name__ == "__main__":

    invname = basename(argv[0])
    args = argv[1:]

    from bdb import BdbQuit
    if debug := int(getenv('DEBUG') or 0):
        import pdb
        from pprint import pp
        err('debug: enabled')
        unsetenv('DEBUG')  # otherwise forked children hang

    try: main()
    except BdbQuit: bomb("debug: stop")
    except SystemExit: raise
    except KeyboardInterrupt: bomb("interrupted")
    except:
        from traceback import print_exc
        print_exc(file=stderr)
        if debug: pdb.post_mortem()
        else: bomb("aborting...")
    finally:  # cpython bug 55589
        try: stdout.flush()
        finally:
            try: stdout.close()
            finally:
                try: stderr.flush()
                except: pass
                finally: stderr.close()
