#!/usr/bin/env python3
"""
hostfill
  replace ipv4 addresses in the input with looked up names in output
"""
__url__     = 'https://github.com/smemsh/utilpy/'
__author__  = 'Scott Mcdermott <scott@smemsh.net>'
__license__ = 'GPL-2.0'

from sys import exit, hexversion
if hexversion < 0x030900f0: exit("minpython: %s" % hexversion)

import argparse

from re import sub
from sys import argv, stdin, stdout, stderr, maxsize
from select import select
from socket import gethostbyaddr, herror
from traceback import print_exc
from subprocess import Popen, PIPE

from os.path import basename
from os import (
    getenv, unsetenv,
    isatty, dup,
    close as osclose,
    EX_OK as EXIT_SUCCESS,
    EX_SOFTWARE as EXIT_FAILURE,
)

###

def err(*args, **kwargs):
    print(*args, file=stderr, **kwargs)

def bomb(*args, **kwargs):
    err(*args, **kwargs)
    exit(EXIT_FAILURE)

###

def process_args():

    global args

    def addopt(p, flagchar, longopt, help=None, /, **kwargs):
        options = list(("-%s --%s" % (flagchar, longopt)).split())
        p.add_argument(*options, help=help, **kwargs)

    def addflag(*args, **kwargs):
        addopt(*args, action='store_true', **kwargs)

    # avoid initial 'usage:' line by providing as formatter_class and
    # providing empty string for 'usage'.  not clear why the interface
    # gives a prefix arg and defaults it, but doesn't allow it to be
    # passed in from anywhere, so we have to override
    #
    class RawTextHelpFormatterEmptyUsageLine(argparse.RawTextHelpFormatter):
        def add_usage(self, usage, actions, groups, prefix=None):
            if prefix is None:
                prefix = ''
            return super(RawTextHelpFormatterEmptyUsageLine, self) \
                .add_usage(usage, actions, groups, prefix)

    p = argparse.ArgumentParser(
        prog            = invname,
        description     = __doc__.strip(),
        allow_abbrev    = False,
        formatter_class = RawTextHelpFormatterEmptyUsageLine,
        usage           = "",
    )
    addflag(p, 's', 'sort', 'filter output through version sort')
    args = p.parse_args(args)


def main():

    process_args()

    def host2ip(match):
        match = match.group(0)
        try: m = gethostbyaddr(match)
        except herror: return match
        if isinstance(m, tuple):
            # [0] hostname str, [1] alias list, [2] addr list
            length = maxsize
            for a in m[1] + [m[0]]:
                # for display, use shortest alias
                if (n := len(a)) < length:
                    length = n
                    shortest = a
            m = shortest
        return m

    if debug == 1:
        breakpoint()

    out = []
    for line in infile:
        out.append(sub(r'\b((\d{1,3}\.){3}\d{1,3})\b', host2ip, line))
    out = ''.join(out).encode()

    if args.sort:
        sortexe = Popen(['sort', '-V', '-'], stdin=PIPE, stdout=PIPE)
        sortout, sorterr = sortexe.communicate(out)
        if sorterr:
            bomb(f"sort error: {sorterr}")
        out = sortout
    print(out.decode(), end='')

    exit(EXIT_SUCCESS)


###

if __name__ == "__main__":

    invname = basename(argv[0])
    args = argv[1:]

    # move stdin, pdb needs stdio fds itself
    stdinfd = stdin.fileno()
    if not isatty(stdinfd):
        try:
            if select([stdin], [], [])[0]:
                infile = open(dup(stdinfd))
                osclose(stdinfd)  # cpython bug 73582
                try: stdin = open('/dev/tty')
                except: pass  # no ctty, but then pdb would not be in use
        except KeyboardInterrupt:
            bomb("interrupted")
    else:
        bomb("must supply input on stdin")

    from bdb import BdbQuit
    if debug := int(getenv('DEBUG') or 0):
        import pdb
        from pprint import pp
        err('debug: enabled')
        unsetenv('DEBUG')  # otherwise forked children hang

    try: main()
    except BdbQuit: bomb("debug: stop")
    except SystemExit: raise
    except KeyboardInterrupt: bomb("interrupted")
    except:
        print_exc(file=stderr)
        if debug: pdb.post_mortem()
        else: bomb("aborting...")
    finally:  # cpython bug 55589
        try: stdout.flush()
        finally:
            try: stdout.close()
            finally:
                try: stderr.flush()
                except: pass
                finally: stderr.close()
